import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function ReferencesLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <>{children}</>;
}
